app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Login
Route::group(['middleware'=>'web'], function () {
	Route::auth();
    Route::get('/home', 'HomeController@index');
    Route::get('/',     'HomeController@index');
});

//Admin
Route::group(['middleware'=>['web','auth'],'prefix' => 'admin','namespace'=>'Admin'], function () {	
	Route::get('/', ['as'=>'dashboard','uses'=>'DashboardController@index']);
	Route::resource('eventos','EventoController');
	Route::resource('categorias','CategoriaController');

	Route::post('indicados/search',['as'=>'admin.indicados.search','uses'=>'IndicadoController@index']);
	//Route::post('indicados/search?page={page}',['as'=>'admin.indicados.search','uses'=>'IndicadoController@index']);	
	Route::get('indicados/createmany',['as'=>'admin.indicados.createmany','uses'=>'IndicadoController@createmany']);		
	Route::post('indicados/createmanystore',['as'=>'admin.indicados.storemany','uses'=>'IndicadoController@createmanystore']);
	Route::resource('indicados','IndicadoController');	
});

//Guest
Route::get('/', ['as'=>'premiacoes','uses'=>'EventoController@index']);
Route::get('indicados/{slug}', ['as'=>'indicados','uses'=>'IndicadoController@indicadosPorEvento']);
Route::post('votacao/enviar', ['as'=>'votacaoenviar','uses'=>'VotacaoController@store']);
Route::get('votacao/view/{id}', ['as'=>'viewvotacao','uses'=>'VotacaoController@view']);

app/Evento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Evento extends Model
{
    protected $table = 'eventos';
    protected $primaryKey = 'evento_id';
    protected $fillable = ['evento_nome','evento_slug', 'evento_ano', 'evento_data','evento_encerrado'];
}

app/Http/Controllers/Admin/EventoController.php
<?php

namespace App\Http\Controllers\Admin;

use Session;
use App\Evento;
use App\Http\Controllers\Controller;
use App\Http\Redirect;
use Illuminate\Http\Request;

class EventoController extends Controller
{
    /**
     * Show the profile for the given Evento.
     *
     * @param  int  $id
     * @return Response
     */
    public function index()
    {        
        $meta = [
            'title' => 'Eventos'
        ];

        $eventos = Evento::paginate(10);
        return view('admin.evento.index')->with(compact('eventos','meta'));        
    }

    public function create(){        
        $meta = [
            'title' => 'Criar Evento'
        ];

        return view('admin.evento.create')->with(compact('meta'));
    }

    public function edit($id){

        $meta = [
            'title' => 'Editar Evento'
        ];

        $evento = Evento::findOrFail($id);
     
        return view('admin.evento.edit')->with(compact('evento','meta'));
    }

    public function store(Request $request){
        $this->validate($request, [
            'evento_nome' => 'required',
            'evento_ano' => 'required',
            'evento_data' => 'required'            
        ]);

        $inputs = $request->all();

        if(!isset($inputs['evento_slug'])){
            $inputs['evento_slug'] = str_slug($inputs['evento_nome'], "-");
        }

        Evento::create($inputs);
        $request->session()->flash('alert-success','Evento criado com sucesso!');

        return redirect()->back();
    }

    public function update($id, Request $request){

        $evento = Evento::findOrFail($id);

        $this->validate($request, [
            'evento_nome' => 'required',
            'evento_ano' => 'required',
            'evento_data' => 'required'            
        ]);        

        $inputs = $request->all();        

        if(!isset($inputs['evento_slug'])){
            $inputs['evento_slug'] = str_slug($inputs['evento_nome'], "-");
        }
        
        $evento->fill($inputs)->save();

        $request->session()->flash('alert-success','Evento atualizado com sucesso!');

        return redirect()->back();
    }

    public function destroy($id)
    {
        $evento = Evento::findOrFail($id);

        $evento->delete();

        Session::flash('alert-success', 'Evento excluído com sucesso!');

        return redirect()->route('admin.eventos.index');
    }
    
}

app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use App\Evento;
use App\Indicado;
use App\Http\Controllers\Controller;

class EventoController extends Controller
{
    /**
     * Show the profile for the given Evento.
     *
     * @param  int  $id
     * @return Response
     */
    public function index()
    {        
        $meta = [
            'title' => 'Eventos'
        ];

        $eventos = Evento::orderby('evento_data','DESC')->get();

        return view('evento.index')->with(compact('eventos','meta'));
    }

    public function edit(){

    }
}

resources/views/admin/evento/create.blade.php
@extends('layouts.admin.default')

@section('content')

<div class="page-title">
	<span class="title">Form Evento Create</span>	
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="card">
			<div class="card-body">
				{!! Form::open([
				    'route' => 'admin.eventos.store'
				]) !!}
				<div class="sub-title">Nome</div>
				<div>					
					{!! Form::text('evento_nome', null, ['class' => 'form-control']) !!}
				</div>
				<div class="sub-title">Ano</div>
				<div>					
					{!! Form::number('evento_ano', null, ['class' => 'form-control','size'=>'4','max'=>9999,'min'=>1]) !!}
				</div>
				<div class="sub-title">Data do Evento</div>
				<div>					
					{!! Form::date('evento_data', null, ['class' => 'form-control']) !!}
				</div>				
				<div class="checkbox">
	              	<div class="checkbox3 checkbox-danger checkbox-inline checkbox-check  checkbox-circle checkbox-light">
	                	{!! Form::checkbox('evento_encerrado',1,null, ['id'=>'checkbox-fa-light-3']) !!}
	                	<label for="checkbox-fa-light-3">Encerrado</label>
	              	</div>
              	</div>

				{!! Form::submit('Gravar Evento', ['class' => 'btn btn-success']) !!}

				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/evento/edit.blade.php
@extends('layouts.admin.default')

@section('content')

<div class="page-title">
	<span class="title">Form Evento</span>	
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="card">
			<div class="card-body">
				
				{{ Form::model($evento, array('route' => array('admin.eventos.update', $evento->evento_id), 'method' => 'PUT')) }}
				
					<div class="sub-title">Nome</div>
					<div>					
						{!! Form::text('evento_nome', null, ['class' => 'form-control']) !!}
					</div>
					<div class="sub-title">Ano</div>
					<div>					
						{!! Form::number('evento_ano', null, ['class' => 'form-control','size'=>'4','max'=>9999,'min'=>1]) !!}
					</div>
					<div class="sub-title">Data do Evento</div>
					<div>					
						{!! Form::date('evento_data', null, ['class' => 'form-control']) !!}
					</div>				
					<div class="checkbox">
		              	<div class="checkbox3 checkbox-danger checkbox-inline checkbox-check  checkbox-circle checkbox-light">
		                	{!! Form::checkbox('evento_encerrado',1,null, ['id'=>'checkbox-fa-light-3']) !!}
		                	<label for="checkbox-fa-light-3">Encerrado</label>
		              	</div>
	              	</div>

				{!! Form::submit('Atualizar Evento', ['class' => 'btn btn-success']) !!}

				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/evento/index.blade.php
@extends('layouts.admin.default')

@section('content')


    <div class="page-title">
        <span class="title">Eventos</span>
        <div class="description">Eventos de premiações cinematográficas e da TV.</div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="card">                
                <div class="card-body">
                	<a href="{{route('admin.eventos.create')}}">
                		<button type="button" class="btn btn-success">Adicionar</button>
                	</a>
                    <table class="table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>#</th> 
								<th>Nome</th>
								<th>Ano</th> 
								<th>Data</th> 
								<th>Encerrado</th>
								<th>Ação</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th> 
								<th>Nome</th> 
								<th>Ano</th> 
								<th>Data</th> 
								<th>Encerrado</th>
								<th>Ação</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach($eventos as $evento)			    
								<tr>
									<th scope="row">{{$evento->evento_id}}</th>
									<td>{{$evento->evento_nome}}</td>
									<td>{{$evento->evento_ano}}</td>
									<td>{{$evento->evento_data}}</td>
									<td>{{returnStatusSimNao($evento->evento_encerrado)}}</td>
									<td>
										<a href="{{route('admin.eventos.edit',['id'=>$evento->evento_id])}}"><button type="button" class="btn btn-info">Editar</button></a>
                                        <!--{!! Form::open([
                                            'method' => 'DELETE',
                                            'route' => ['admin.eventos.destroy', $evento->id]
                                        ]) !!}
                                            {!! Form::submit('Excluir', ['class' => 'btn btn-danger']) !!}
                                        {!! Form::close() !!}-->
									</td>				
								</tr> 
							@endforeach
                        </tbody>
                    </table>
                    <div class="pull-right">
                        {{$eventos->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>    
@endsection