app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Login
Route::group(['middleware'=>'web'], function () {
	Route::auth();
    Route::get('/home', 'HomeController@index');
    Route::get('/',     'HomeController@index');
});

//Admin
Route::group(['middleware'=>['web','auth'],'prefix' => 'admin','namespace'=>'Admin'], function () {	
	Route::get('/', ['as'=>'dashboard','uses'=>'DashboardController@index']);
	Route::resource('eventos','EventoController');
	Route::resource('categorias','CategoriaController');

	Route::post('indicados/search',['as'=>'admin.indicados.search','uses'=>'IndicadoController@index']);
	//Route::post('indicados/search?page={page}',['as'=>'admin.indicados.search','uses'=>'IndicadoController@index']);	
	Route::get('indicados/createmany',['as'=>'admin.indicados.createmany','uses'=>'IndicadoController@createmany']);		
	Route::post('indicados/createmanystore',['as'=>'admin.indicados.storemany','uses'=>'IndicadoController@createmanystore']);
	Route::resource('indicados','IndicadoController');	
});

//Guest
Route::get('/', ['as'=>'premiacoes','uses'=>'EventoController@index']);
Route::get('indicados/{slug}', ['as'=>'indicados','uses'=>'IndicadoController@indicadosPorEvento']);
Route::post('votacao/enviar', ['as'=>'votacaoenviar','uses'=>'VotacaoController@store']);
Route::get('votacao/view/{id}', ['as'=>'viewvotacao','uses'=>'VotacaoController@view']);

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $table = 'categorias';
    protected $primaryKey = 'categoria_id';
    protected $fillable = ['categoria_nome'];
}

app/Http/Controllers/Admin/CategoriaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Categoria;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriaController extends Controller
{

    public function index()
    {        
        $meta = [
            'title' => 'Categorias'
        ];

        $categorias = Categoria::paginate(10);
        return view('admin.categoria.index')->with(compact('categorias','meta'));
    }

    public function create(){        
        $meta = [
            'title' => 'Criar Categoria'
        ];

        return view('admin.categoria.create')->with(compact('meta'));
    }

    public function edit($id){

        $meta = [
            'title' => 'Editar Evento'
        ];

        $categoria = Categoria::findOrFail($id);
     
        return view('admin.categoria.edit')->with(compact('categoria','meta'));
    }

    public function store(Request $request){
        $this->validate($request, [
            'categoria_nome' => 'required'
        ]);

        $inputs = $request->all();

        Categoria::create($inputs);
        $request->session()->flash('alert-success','Categoria criada com sucesso!');

        return redirect()->back();
    }

    public function update($id, Request $request){

        $categoria = Categoria::findOrFail($id);

        $this->validate($request, [
            'categoria_nome' => 'required'          
        ]);

        $inputs = $request->all();
        
        $categoria->fill($inputs)->save();

        $request->session()->flash('alert-success','Categoria atualizado com sucesso!');

        return redirect()->back();
    }

    public function destroy($id)
    {
        $categoria = Evento::findOrFail($id);

        $categoria->delete();

        Session::flash('alert-success', 'Evento excluído com sucesso!');

        return redirect()->route('admin.eventos.index');
    }
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Categoria;
use App\Http\Controllers\Controller;

class CategoriaController extends Controller
{
    /**
     * Show the profile for the given Evento.
     *
     * @param  int  $id
     * @return Response
     */
    public function index()
    {
        
        $meta = [
            'title' => 'Categorias'
        ];

        $categorias = Categoria::all();        
        return view('categoria.index')->with(compact('categorias','meta'));
    }
}

resources/views/admin/categoria/create.blade.php
@extends('layouts.admin.default')

@section('content')

<div class="page-title">
	<span class="title">Form Categoria Create</span>	
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="card">
			<div class="card-body">
				{!! Form::open([
				    'route' => 'admin.categorias.store'
				]) !!}
				<div class="sub-title">Nome</div>
				<div>					
					{!! Form::text('categoria_nome', null, ['class' => 'form-control']) !!}
				</div>						

				{!! Form::submit('Gravar Categoria', ['class' => 'btn btn-success']) !!}

				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/categoria/edit.blade.php
@extends('layouts.admin.default')

@section('content')

<div class="page-title">
	<span class="title">Form Categoria</span>	
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="card">
			<div class="card-body">
				
				{{ Form::model($categoria, array('route' => array('admin.categorias.update', $categoria->categoria_id), 'method' => 'PUT')) }}
				
					<div class="sub-title">Nome</div>
					<div>					
						{!! Form::text('categoria_nome', null, ['class' => 'form-control']) !!}
					</div>					

				{!! Form::submit('Atualizar Categoria', ['class' => 'btn btn-success']) !!}

				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/categoria/index.blade.php
@extends('layouts.admin.default')

@section('content')

    <div class="page-title">
        <span class="title">Categorias</span>
        <div class="description">Categorias dos eventos.</div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="card">                
                <div class="card-body">
                	<a href="{{route('admin.categorias.create')}}">
                		<button type="button" class="btn btn-success">Adicionar</button>
                	</a>
                    <table class="table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>#</th> 
								<th>Nome</th>								
								<th>Ação</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th> 
								<th>Nome</th> 								
								<th>Ação</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach($categorias as $categoria)
								<tr>
									<th scope="row">{{$categoria->categoria_id}}</th>
									<td>{{$categoria->categoria_nome}}</td>															
									<td>
										<a href="{{route('admin.categorias.edit',['id'=>$categoria->categoria_id])}}"><button type="button" class="btn btn-info">Editar</button></a>
                                        <!--{!! Form::open([
                                            'method' => 'DELETE',
                                            'route' => ['admin.categorias.destroy', $categoria->id]
                                        ]) !!}
                                            {!! Form::submit('Excluir', ['class' => 'btn btn-danger']) !!}
                                        {!! Form::close() !!}-->
									</td>				
								</tr> 
							@endforeach
                        </tbody>
                    </table>
                    <div class="pull-right">
                        {{$categorias->render()}}
                    </div>              
                </div>
            </div>
        </div>
    </div>

@endsection